#!/bin/bash

pushd common-libs/3rd-party/ >> /dev/null
tar -xvzf libevent-2.0.18-stable.tar.gz
tar -xvzf glib-2.32.0.tar.gz
popd  >> /dev/null
pushd common-libs/3rd-party/libevent-2.0.18-stable/ >> /dev/null
./configure && make
popd  >> /dev/null
#pushd ./common-libs/3rd-party/derived-lib >> /dev/null
#make 
#popd >> /dev/null
#pushd ./common-libs/3rd-party/quagga-lib >> /dev/null
#make
#popd >> /dev/null
#pushd ./common-libs/mul-lib >> /dev/null
#make
#popd >> /dev/null
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
pushd common-libs/3rd-party/glib-2.32.0/ >> /dev/null 
./configure && make
popd
